#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

restart-taffybar

# Pidgin chat client
if [ -z "$(pgrep pidgin)" ] ; then
    pidgin &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
    system-config-printer-applet &
fi

# Start redshift with applet
# if [ -z "(pgrep redshift-gtk)" ] ; then
#     redshift-gtk &
# fi

# Emacs server
if [ -z "$(pgrep emacs)" ]; then
    emacs --daemon &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested)
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

# Screen saver and locker
if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver -no-splash &
fi

# Lock on sleep
if [ -z "$(pgrep xss-lock)" ] ; then
    xss-lock -- lock &
fi

# Volume control
if [ -z "$(pgrep pasystray)" ] ; then
    pasystray --volume-inc 5 --max-volume 100 &
fi

# Battery icon
if [ -z "$(pgrep cbatticon)" ] ; then
    cbatticon --command-critical-level "systemctl suspend" &
fi

# On login, we unlock the ssh keychain so we're not prompted for
# passphrases later. We pipe /dev/null to ssh-add to make it realize
# it's not running in a terminal. Otherwise, it won't launch the prompt.
#
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

export SSH_ASKPASS="/usr/lib/ssh/ssh-askpass"
cat /dev/null | ssh-add &
